CREATE USER 'mascotitastockroot'@'localhost' IDENTIFIED BY 'm4sc0t1t4s';
GRANT CREATE ROLE ON *.* TO 'mascotitastock'@'localhost';
GRANT CREATE USER ON *.* TO 'mascotitastock'@'localhost';
GRANT DROP ROLE ON *.* TO 'mascotitastock'@'localhost';
GRANT EVENT ON *.* TO 'mascotitastock'@'localhost';
GRANT FILE ON *.* TO 'mascotitastock'@'localhost';
GRANT PROCESS ON *.* TO 'mascotitastock'@'localhost';
GRANT RELOAD ON *.* TO 'mascotitastock'@'localhost';
GRANT REPLICATION CLIENT ON *.* TO 'mascotitastock'@'localhost';
GRANT REPLICATION SLAVE ON *.* TO 'mascotitastock'@'localhost';
GRANT SHOW DATABASES ON *.* TO 'mascotitastock'@'localhost';
GRANT SHUTDOWN ON *.* TO 'mascotitastock'@'localhost';
GRANT SUPER ON *.* TO 'mascotitastock'@'localhost';
GRANT CREATE TABLESPACE ON *.* TO 'mascotitastock'@'localhost';
GRANT INNODB_REDO_LOG_ARCHIVE ON *.* TO 'mascotitastock'@'localhost';
GRANT ENCRYPTION_KEY_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT CONNECTION_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT TABLE_ENCRYPTION_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT ROLE_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT REPLICATION_SLAVE_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT BINLOG_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT AUDIT_ABORT_EXEMPT ON *.* TO 'mascotitastock'@'localhost';
GRANT SERVICE_CONNECTION_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT GROUP_REPLICATION_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT PASSWORDLESS_USER_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT XA_RECOVER_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT PERSIST_RO_VARIABLES_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT SHOW_ROUTINE ON *.* TO 'mascotitastock'@'localhost';
GRANT BACKUP_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT GROUP_REPLICATION_STREAM ON *.* TO 'mascotitastock'@'localhost';
GRANT CLONE_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT OPTIMIZE_LOCAL_TABLE ON *.* TO 'mascotitastock'@'localhost';
GRANT SESSION_VARIABLES_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT RESOURCE_GROUP_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT FIREWALL_EXEMPT ON *.* TO 'mascotitastock'@'localhost';
GRANT RESOURCE_GROUP_USER ON *.* TO 'mascotitastock'@'localhost';
GRANT BINLOG_ENCRYPTION_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT APPLICATION_PASSWORD_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT SYSTEM_USER ON *.* TO 'mascotitastock'@'localhost';
GRANT FLUSH_OPTIMIZER_COSTS ON *.* TO 'mascotitastock'@'localhost';
GRANT AUDIT_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT TELEMETRY_LOG_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT INNODB_REDO_LOG_ENABLE ON *.* TO 'mascotitastock'@'localhost';
GRANT REPLICATION_APPLIER ON *.* TO 'mascotitastock'@'localhost';
GRANT FLUSH_STATUS ON *.* TO 'mascotitastock'@'localhost';
GRANT FLUSH_USER_RESOURCES ON *.* TO 'mascotitastock'@'localhost';
GRANT FLUSH_TABLES ON *.* TO 'mascotitastock'@'localhost';
GRANT SET_ANY_DEFINER ON *.* TO 'mascotitastock'@'localhost';
GRANT FLUSH_PRIVILEGES ON *.* TO 'mascotitastock'@'localhost';
GRANT AUTHENTICATION_POLICY_ADMIN ON *.* TO 'mascotitastock'@'localhost';
GRANT SENSITIVE_VARIABLES_OBSERVER ON *.* TO 'mascotitastock'@'localhost';
GRANT ALLOW_NONEXISTENT_DEFINER ON *.* TO 'mascotitastock'@'localhost';
GRANT TRANSACTION_GTID_TAG ON *.* TO 'mascotitastock'@'localhost';
GRANT GRANT OPTION ON *.* TO 'mascotitastock'@'localhost';
GRANT ALTER ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT CREATE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT CREATE VIEW ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT DELETE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT DROP ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT GRANT OPTION ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT INDEX ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT INSERT ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT REFERENCES ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT SELECT ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT SHOW VIEW ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT TRIGGER ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT UPDATE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT ALTER ROUTINE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT CREATE ROUTINE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT CREATE TEMPORARY TABLES ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT EXECUTE ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT LOCK TABLES ON mascotitastock.* TO 'mascotitastock'@'localhost';
GRANT GRANT OPTION ON mascotitastock.* TO 'mascotitastock'@'localhost';
